import { SourceDocumentReference } from './source-document-reference.model';

/**
 * Answer model - A text response generated by the backend RAG system
 */
export interface Answer {
  content: string;                    // The answer text
  sources: SourceDocumentReference[]; // Documents used to generate answer
  timestamp: Date;                    // When the answer was received
  isStreaming?: boolean;              // True while streaming in progress
}
